language: perl
os:
  - linux
  - osx
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
before_install:
    - nvm install $(cat .nvmrc)
    - nvm use $(cat .nvmrc)
    - perl --version
    - node --version
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
    - export PATH=$HOME/.yarn/bin:$PATH
    # - export PERL5OPT="-I${HOME}/perl5/lib/perl5"
    - echo $PERL5OPT
    - echo $TRAVIS_OS_NAME
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cpanm PadWalker; fi
cache:
  yarn: true
  bundler: true
  directories:
  - node_modules # NPM packages
install:
    - travis_retry yarn
stages:
  - test
  - name: release
    if: branch = master AND type = push AND fork = false

script:
    - yarn tslint
    - travis_retry yarn test # This happens on linux, should investigate
jobs:
  include:
    - stage: release
      language: node_js
      node_js: '8'
      script:
        - yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
